// RUN: mlir-opt -load-pass-plugin=%mlir_lib_dir/LoopPassBeginEnd_Chizhov_Maxim_FIIT3_MLIR%shlibext \
// RUN: --pass-pipeline="builtin.module(LoopPassBeginEnd_Chizhov_Maxim_FIIT3_MLIR)" %s | FileCheck %s

module {
  func.func private @trace_loop_iter_begin() -> ()
  func.func private @trace_loop_iter_end() -> ()

  // CHECK-LABEL: func.func @affine_loop
  // CHECK-NEXT: %c0 = arith.constant 0 : index
  // CHECK-NEXT: %c10 = arith.constant 10 : index
  // CHECK-NEXT: affine.for %{{.*}} = %c0 to %c10 {
  // CHECK-NEXT:   call @trace_loop_iter_begin() : () -> ()
  // CHECK-NEXT:   "test.op"() : () -> ()
  // CHECK-NEXT:   call @trace_loop_iter_end() : () -> ()
  func.func @affine_loop() {
    %c0 = arith.constant 0 : index
    %c10 = arith.constant 10 : index

    affine.for %i = %c0 to %c10 {
      "test.op"() : () -> ()
    }
    return
  }
}

module {
  func.func private @trace_loop_iter_begin() -> ()
  func.func private @trace_loop_iter_end() -> ()

  // CHECK-LABEL: func.func @scf_loop
  // CHECK-NEXT: %c0 = arith.constant 0 : index
  // CHECK-NEXT: %c1 = arith.constant 1 : index
  // CHECK-NEXT: %c10 = arith.constant 10 : index
  // CHECK-NEXT: scf.for %{{.*}} = %c0 to %c10 step %c1 {
  // CHECK-NEXT:   call @trace_loop_iter_begin() : () -> ()
  // CHECK-NEXT:   "test.op"() : () -> ()
  // CHECK-NEXT:   call @trace_loop_iter_end() : () -> ()
  func.func @scf_loop() {
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c10 = arith.constant 10 : index

    scf.for %i = %c0 to %c10 step %c1 {
      "test.op"() : () -> ()
    }

    return
  }
}

module {
  func.func private @trace_loop_iter_begin() -> ()
  func.func private @trace_loop_iter_end() -> ()

  // CHECK-LABEL: func.func @scf_while
  // CHECK-NEXT: %c0 = arith.constant 0 : index
  // CHECK-NEXT: %c1 = arith.constant 1 : index
  // CHECK-NEXT: %c10 = arith.constant 10 : index
  // CHECK-NEXT: %0 = scf.while (%arg0 = %c0) : (index) -> index {
  // CHECK-NEXT:   %1 = arith.cmpi slt, %arg0, %c10 : index
  // CHECK-NEXT:   scf.condition(%1) %arg0 : index
  // CHECK-NEXT: } do {
  // CHECK-NEXT:   ^bb0(%arg0: index):
  // CHECK-NEXT:     call @trace_loop_iter_begin() : () -> ()
  // CHECK-NEXT:     "test.op"() : () -> ()
  // CHECK-NEXT:     %1 = arith.addi %arg0, %c1 : index
  // CHECK-NEXT:     call @trace_loop_iter_end() : () -> ()
  // CHECK-NEXT:     scf.yield %1 : index


  func.func @scf_while() {
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c10 = arith.constant 10 : index

    %init = scf.while (%i = %c0) : (index) -> (index) {
      %cond = arith.cmpi "slt", %i, %c10 : index
      scf.condition(%cond) %i : index
    } do {
      ^bb0(%i_in: index):
        "test.op"() : () -> ()
        %inc = arith.addi %i_in, %c1 : index
        scf.yield %inc : index
    }

    return
  }
}
